# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YDM(object):
    def setupUi(self, YDM):
        YDM.setObjectName("YDM")
        YDM.resize(1028, 480)
        YDM.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(YDM)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1011, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.video_btn = QtWidgets.QRadioButton(self.frame)
        self.video_btn.setChecked(True)
        self.video_btn.setObjectName("video_btn")
        self.horizontalLayout.addWidget(self.video_btn)
        self.audio_btn = QtWidgets.QRadioButton(self.frame)
        self.audio_btn.setChecked(False)
        self.audio_btn.setObjectName("audio_btn")
        self.horizontalLayout.addWidget(self.audio_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.qualitybox = QtWidgets.QComboBox(self.frame)
        self.qualitybox.setObjectName("qualitybox")
        self.qualitybox.addItem("")
        self.qualitybox.addItem("")
        self.qualitybox.addItem("")
        self.horizontalLayout_2.addWidget(self.qualitybox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_3.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_3.addWidget(self.search_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.exit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_3.addWidget(self.exit_btn)
        YDM.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(YDM)
        self.statusbar.setObjectName("statusbar")
        YDM.setStatusBar(self.statusbar)

        self.retranslateUi(YDM)
        self.search_input.returnPressed.connect(self.search_btn.animateClick)
        QtCore.QMetaObject.connectSlotsByName(YDM)

    def retranslateUi(self, YDM):
        _translate = QtCore.QCoreApplication.translate
        YDM.setWindowTitle(_translate("YDM", "Youtube Download Manger (YDM)"))
        self.video_btn.setText(_translate("YDM", "Video (mp4)"))
        self.audio_btn.setText(_translate("YDM", "Audio (mp3)"))
        self.label.setText(_translate("YDM", "Quality"))
        self.qualitybox.setItemText(0, _translate("YDM", "144p"))
        self.qualitybox.setItemText(1, _translate("YDM", "360p"))
        self.qualitybox.setItemText(2, _translate("YDM", "720p"))
        self.search_btn.setText(_translate("YDM", "Go"))
        self.exit_btn.setText(_translate("YDM", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YDM = QtWidgets.QMainWindow()
    ui = Ui_YDM()
    ui.setupUi(YDM)
    YDM.show()
    sys.exit(app.exec_())
